### ISSUE TITLE
Requires kvm host machine to be same series as unit

### ISSUE THREAD

**Issue by hatched** [juju/juju-bundlelib#31]
The following bundle import fails with the error `charm cs:trusty/keystone-25 cannot be deployed to machine with different series precise` I don't believe the host should matter because the unit will be deployed into a kvm on the host machine.

```
series: trusty
services: 
  "openstack-dashboard": 
    charm: "cs:trusty/openstack-dashboard-14"
    num_units: 1
    annotations: 
      "gui-x": "-335"
      "gui-y": "-330"
    to: 
      - "lxc:ceph/0"
  keystone: 
    charm: "cs:trusty/keystone-25"
    num_units: 1
    annotations: 
      "gui-x": "-103"
      "gui-y": "-130"
    to: 
      - "kvm:2"
  glance: 
    charm: "cs:trusty/glance-20"
    num_units: 1
    annotations: 
      "gui-x": "152"
      "gui-y": "-400"
    to: 
      - "1"
  ceph: 
    charm: "cs:trusty/ceph-36"
    num_units: 1
    annotations: 
      "gui-x": "-382"
      "gui-y": "8"
    to: 
      - "0"
relations: []
machines: 
  "0": 
    series: trusty
    constraints: "arch=amd64 cpu-cores=1 cpu-power=100 mem=1740 root-disk=8192"
  "1": 
    series: trusty
    constraints: "arch=amd64 cpu-cores=1 cpu-power=100 mem=1740 root-disk=8192"
  "2": 
    series: precise
    constraints: "arch=amd64 cpu-cores=1 cpu-power=100 mem=1740 root-disk=8192"
```
