### ISSUE TITLE
Invalid placement syntax not caught in proof

### ISSUE THREAD

**Issue by AdamIsrael** [juju/juju-bundlelib#50]
I'm reviewing a bundle that passes `charm proof` but fails to push to the charm store when the lxd placement directive omits a machine id or unit name.

```bash
$ charm push . cs:~midonet-charmers/bundle/openstack-midonet-liberty
ERROR cannot post archive: bundle verification failed: ["invalid placement syntax \"lxc:\"","invalid placement syntax \"lxc:\"","invalid placement syntax \"lxc:\""]
```

From bundle.yaml:
```yaml
  mysql:
    charm: "cs:trusty/mysql-18"
    num_units: 1
    options:
      "max-connections": 500
    annotations:
      "gui-x": "531"
      "gui-y": "237.2949192431123"
    to:
      - "lxc:"
```
I've verified that `charm push` succeeds if the lxc: placement directive is removed.
