### ISSUE TITLE
availability zone missing in _CONSTRAINTS

### ISSUE THREAD

**Issue by makyo** [juju/juju-bundlelib#53]
Via @huwshimi:

When I try and deploy a bundle with availability zones e.g.

```
machines: 
  "0": 
    series: precise
    constraints: "arch=amd64 cpu-cores=1 cpu-power=300 mem=3840 root-disk=8192 availability-zone=ap-southeast-2a"
```

I get this follow error:

```
The following errors occurred while retrieving bundle changes: invalid constraints "arch=amd64 cpu-cores=1 cpu-power=300 mem=3840 root-disk=8192 availability-zone=ap-southeast-2b" in machine "1": unknown constraint "availability-zone", invalid constraints "arch=amd64 cpu-cores=1 cpu-power=300 mem=3840 root-disk=8192 availability-zone=ap-southeast-2a" in machine "0": unknown constraint "availability-zone"
```
